services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: e-commerce
    networks:
      - freecodecamp
  test-db:
    image: postgres:13 
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: e-commerce
    networks:
      - freecodecamp
networks:
  freecodecamp:
